import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import Script from "next/script";

import "./globals.css";
import { AuthProvider } from "@/features/auth/AuthContext";
import DarkModeProvider from "@/features/dark-mode/DarkModeProvider";
import { DARK_MODE_LOCAL_STORAGE_KEY } from "@/features/dark-mode/consts";

const merriweather = Merriweather({
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			// default dark mode
			className="dark overflow-hidden"
		>
			<head>
				<Script id="dark-mode-script">
					{`if (localStorage['${DARK_MODE_LOCAL_STORAGE_KEY}'] === 'dark' || (!('${DARK_MODE_LOCAL_STORAGE_KEY}' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark')
                } else {
                  document.documentElement.classList.remove('dark')
                }`}
				</Script>
			</head>
			<body className={merriweather.className}>
				<AuthProvider>
					<DarkModeProvider>{children}</DarkModeProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
