import { KumaRegistry } from "@kuma-ui/next-plugin/registry";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

import "./globals.css";
import DarkModeProvider from "@/components/dark-mode-provider";
import { DARK_MODE_LOCAL_STORAGE_KEY } from "@/helpers/dark-mode";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<Script id="dark-mode-script">
					{`if (localStorage['${DARK_MODE_LOCAL_STORAGE_KEY}'] === 'dark' || (!('${DARK_MODE_LOCAL_STORAGE_KEY}' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.documentElement.classList.add('dark')
                } else {
                  document.documentElement.classList.remove('dark')
                }`}
				</Script>
			</head>
			<body className={inter.className}>
				<DarkModeProvider>
					<KumaRegistry>{children}</KumaRegistry>
				</DarkModeProvider>
			</body>
		</html>
	);
}
